[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Access-Control-Allow-Origin = "https://mail.google.com"
    AMP-Access-Control-Allow-Source-Origin = "amp@gmail.dev"
    Access-Control-Expose-Headers = "AMP-Access-Control-Allow-Source-Origin"

    #  Multi-value headers are expressed with multi-line strings
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
