[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW"
    Access-Control-Allow-Origin = "*"
    AMP-Access-Control-Allow-Source-Origin = "amp@gmail.dev"
    Access-Control-Expose-Headers = "AMP-Access-Control-Allow-Source-Origin"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

    #  Multi-value headers are expressed with multi-line strings
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

[[redirects]]
  from = "/"
  to = "/test.json"
  status = 301
  force = true
  query = {path = ":path"}

[[redirects]]
  from = "/1"
  to = "https://contacts.google.com/widget/hovercard/v/2?hl=en-GB&origin=https%3A%2F%2Fsites.google.com&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.l2ZUC8FxqV8.O%2Fd%3D1%2Frs%3DAHpOoo9xAAkaXO7Lqf7-9uTpZLtrkpWaXQ%2Fm%3D__features__#id=I__HC_94253229&_gfid=I__HC_94253229&parent=https%3A%2F%2Fsites.google.com&pfname=&rpctoken=12116901"
  status = 301
  force = true

[[redirects]]
  from = "/2"
  to = "https://myaccount.google.com/profile-picture?origin=https%3A%2F%2Fsites.google.com&amp;hostId=ma&amp;theme=light"
  status = 301
  force = true

  [[redirects]]
  from = "/3"
  to = "https://docs.google.com/drivesharing/driveshare?id=152iRo0ZqWkqZAy8zhAToUdTQl3jWlOYHDJQ4GbLXK2g&resourcekey=["152iRo0ZqWkqZAy8zhAToUdTQl3jWlOYHDJQ4GbLXK2g"]&themeColor=2&themeMode=1&foreignService=kix&gaiaService=writely&shareService=kix&command=init_share&subapp=10&popupWindowsEnabled=true&shareUiType=default&hl=en-GB&authuser=0&rand=1737711467419&locationHint=unknown&preload=false&triggerInstantMs=1737711467418&initialCommandHint=settings&origin=https%3A%2F%2Fsites.google.com"
  status = 301
  force = true

  [[redirects]]
  from = "/4"
  to = "https://contacts.google.com/widget/hovercard/v/2?hl=en-GB&origin=https%3A%2F%2Fsites.google.com&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.l2ZUC8FxqV8.O%2Fd%3D1%2Frs%3DAHpOoo9xAAkaXO7Lqf7-9uTpZLtrkpWaXQ%2Fm%3D__features__#id=I__HC_94253229&_gfid=I__HC_94253229&parent=https%3A%2F%2Fsites.google.com&pfname=&rpctoken=12116901"
  status = 301
  force = true

  [[redirects]]
  from = "/5"
  to = "https://contacts.google.com/widget/hovercard/v/2?hl=en-GB&origin=https%3A%2F%2Fsites.google.com&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.l2ZUC8FxqV8.O%2Fd%3D1%2Frs%3DAHpOoo9xAAkaXO7Lqf7-9uTpZLtrkpWaXQ%2Fm%3D__features__#id=I__HC_94253229&_gfid=I__HC_94253229&parent=https%3A%2F%2Fsites.google.com&pfname=&rpctoken=12116901"
  status = 301
  force = true

  [[redirects]]
  from = "/6"
  to = "https://contacts.google.com/widget/hovercard/v/2?hl=en-GB&origin=https%3A%2F%2Fsites.google.com&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.l2ZUC8FxqV8.O%2Fd%3D1%2Frs%3DAHpOoo9xAAkaXO7Lqf7-9uTpZLtrkpWaXQ%2Fm%3D__features__#id=I__HC_94253229&_gfid=I__HC_94253229&parent=https%3A%2F%2Fsites.google.com&pfname=&rpctoken=12116901"
  status = 301
  force = true
