[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW"
    Access-Control-Allow-Origin = "*"
    AMP-Access-Control-Allow-Source-Origin = "amp@gmail.dev"
    Access-Control-Expose-Headers = "AMP-Access-Control-Allow-Source-Origin"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

    #  Multi-value headers are expressed with multi-line strings
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

[[redirects]]
  from = "/"
  to = "/test.json"
  status = 301
  force = true
  query = {path = ":path"}

[[redirects]]
  from = "/hello"
  to = "https://ogs.google.com/u/2/widget/app?eom=1&awwd=1&origin=https%3A%2F%2Fsites.google.com&cn=app&pid=269&spid=192&hl=en-GB"
  status = 301
  force = true
