[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW"
    Access-Control-Allow-Origin = "*"
    jslink = "javascript:alert(1);"
    datalink = "data:text/html,asdfgh"
    urlbiasa = "https://google.com"
    
    #  Multi-value headers are expressed with multi-line strings
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

[[redirects]]
  from = "/"
  to = "/test.json"
  status = 301
  force = true
  query = {path = ":path"}

[[redirects]]
  from = "/1"
  to = "https://sites.google.com/u/0/d/1LQYLJyJHZDXsvfCRb3guj7YRA-SNVA1v/pagediffpublished?prt=AEvxacJIRR1xuDDWia_A4K9h4Bn6qfslcD1RnCTvEr5CJK3hQGyNACI-lnHNi5fB6IwdaIjcFVmHIOdqJ1NpnqnrqWG3qpmcZOnO2Q1zWENfz9hbw-kZiAEoU24pVgJedP3SnmCPGRf3ufyV6WjnuLHOW5jIeMH-sAB4ewdmGvHRPQkNfR6mlRPLlqNv8A%3D%3D"
  status = 301
  force = true

[[redirects]]
  from = "/2"
  to = "https://docs.google.com/document/d/152iRo0ZqWkqZAy8zhAToUdTQl3jWlOYHDJQ4GbLXK2g/preview?tab=t.0"
  status = 301
  force = true

  [[redirects]]
  from = "/3"
  to = "https://abusereporting-pa.clients6.google.com/static/proxy.html?usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.lb.en.5oZHy0SiJxw.O%2Fd%3D1%2Frs%3DAHpOoo-Hry6DG-RE4t9kNz_t6hiwmwXOmA%2Fm%3D__features__#parent=https%3A%2F%2Fsites.google.com&rpctoken=470266637"
  status = 301
  force = true

  [[redirects]]
  from = "/4"
  to = "https://contacts.google.com/widget/hovercard/v/2?hl=en-GB&origin=https%3A%2F%2Fsites.google.com&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.l2ZUC8FxqV8.O%2Fd%3D1%2Frs%3DAHpOoo9xAAkaXO7Lqf7-9uTpZLtrkpWaXQ%2Fm%3D__features__#id=I__HC_94253229&_gfid=I__HC_94253229&parent=https%3A%2F%2Fsites.google.com&pfname=&rpctoken=12116901"
  status = 301
  force = true

  [[redirects]]
  from = "/5"
  to = "https://contacts.google.com/widget/hovercard/v/2?hl=en-GB&origin=https%3A%2F%2Fsites.google.com&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.l2ZUC8FxqV8.O%2Fd%3D1%2Frs%3DAHpOoo9xAAkaXO7Lqf7-9uTpZLtrkpWaXQ%2Fm%3D__features__#id=I__HC_94253229&_gfid=I__HC_94253229&parent=https%3A%2F%2Fsites.google.com&pfname=&rpctoken=12116901"
  status = 301
  force = true

  [[redirects]]
  from = "/6"
  to = "https://glittering-mooncake-dda111.netlify.app/alert.js"
  status = 301
  force = true
